config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
    root 'home#two'
    post 'home/reply/(:id)' => 'home#test1', as: 'reply_view'
    post 'home/write_reply', as: 'reply_reply'

    match ":controller(/:action(/:id))", :via => [:post, :get]
    
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :replies
    belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/univ.rb
class Univ < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :replies
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def one
    @posts2 = Post.all
  
      
  end

  def two
    @posts3 =  Post.all
    @posts2 = Post.last(3)    
    if current_user
    @mylog = Post.where(:univ => current_user.univ).last(3)
    @mylog2 = Post.where(:user_id => current_user.id).last(3)
    end
  end

  def three
    @posts3 = Post.all   
    if params[:search2].nil?
      @mylog = Post.where(:univ => params[:search])
    else  
      @mylog2 = Post.where(:user_id => params[:search2])
    end
  end
  
  def goo
    
  end
  
  def test1
    
    @detail = Post.find(params[:id]) 

  end
  
  def test2
    @posts2 = Post.all
  
  end
  
  def test3
    @posts2 = Post.all
  
  end
  
    
  def test4
      @posts2 = Post.all    
  
  end
  
  def test5
      
      
  end
  
  def write_univ
      univ = Univ.new
      univ.univ = params[:univ]
      univ.save
      redirect_to(:back)
    
  end
  
  def write
    post = Post.new
      post.img = current_user.img
      post.age = current_user.age
      post.email = params[:email]
        post.sex = current_user.sex
        post.univ = current_user.univ
        post.place = params[:place]
        post.number = params[:number]
        post.content = params[:content]
        post.user_id = current_user.id
        post.save
     redirect_to '/'
  end

  def reply
      @detail = Post.find(params[:id]) 

  end

  
  def write_reply
    # 해당 게시물의 댓글들의 이메일들 중 하나가 내 이메일이랑 일치했을 때 
        my_reply = Reply.new
        my_reply.univ = params[:univ]
        my_reply.img = params[:img]
        my_reply.age = params[:age]
        my_reply.post_id = params[:post_id]
        my_reply.content = params[:myreply]
        my_reply.user_id = current_user.id
        
        unless(Post.find(params[:post_id]).replies.where(user_id: current_user.id).first) #사실 이게 될런지 안될런지 모르겠음 ㅋㅋ 근데 안되면 each do로 하나씩 검사해주면 될듯
             my_reply.save
        else
            #나중에 자바스크립트 alert넣어주기!(이미 댓글을 등록하셨습니다)
        end
      redirect_to(:back)
  end
    
  
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    
     devise_parameter_sanitizer.for(:sign_up) << :sex
     devise_parameter_sanitizer.for(:sign_up) << :age
     devise_parameter_sanitizer.for(:sign_up) << :univ
     devise_parameter_sanitizer.for(:sign_up) << :number
     devise_parameter_sanitizer.for(:sign_up) << :img
     

  end
  
 

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
     devise_parameter_sanitizer.for(:account_update) << :sex
     devise_parameter_sanitizer.for(:account_update) << :age
     devise_parameter_sanitizer.for(:account_update) << :univ
     devise_parameter_sanitizer.for(:account_update) << :number
     devise_parameter_sanitizer.for(:account_update) << :img
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
    
        def resource_name
          :user
        end
        
        def resource
          @resource ||= User.new
        end

    
end

app/views/home/_header.erb
  <!--header start-->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="/home/two" class="logo"><img src="/assets/오미팅로고.png" style="width:40px; height:40px;" class="img-circle">&nbsp <b>새내기 미팅처럼</b></a>
            
            <!--logo end-->
            
            <% if current_user.nil? %>    
            <div class="top-menu row pull-right" style="margin-top:0px; text-align:right">


<form class="new_user navbar-form form-group" id="new_user" action="/users/sign_in" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="nmI9PI3D3rqX4ir864hJDqEU2RXIabk5ZuzTEIl1+J0eRWL0wrUTL9q8qfVUWfgpSZ/x9gf9RcFPwo0bjhGGJg==">
                
    <input class="form-control" autofocus="autofocus" type="email"  name="user[email]" id="user_email" preholder="email">



    <input class="form-control" autocomplete="off" type="password" name="user[password]" id="user_password">

      <input name="user[remember_me]" type="hidden" value="0"><input type="checkbox" value="1" name="user[remember_me]" id="user_remember_me">
      <label for="user_remember_me" class="from-control">Remember me</label>


    <button type="submit" name="commit" class="btn btn-info" value="Log in"> Sign in </button>
</form>          
            	
            	<button type="button" class="btn-default" data-toggle="modal" data-target="#myModal2">혹시 처음이신가요?</button>
            	

                

            <% else %>
            
            	<div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><a class="logout" href="/users/sign_out">Logout</a></li>
            	</ul>
            <% end %>	
            </div>
            </div>
        </header>
      <!--header end-->

app/views/home/_mylog.erb
<div class="row">	  
    <% @mylog.reverse.each do |x| %>   
        <%= link_to reply_view_path(x.id), method:'post' do %>
        
        <% content_tag :div %>
        
            <div class="[ col-xs-12 col-sm-4 ] goodd">
                <div class="[ panel panel-default ] panel-google-plus">
                    
                    <div style="font-family: 'Hanna';" class="panel-heading">
                        <img class="[ img-circle pull-left ]" src="/assets/<%= x.univ %>.jpg" class="img-circle" width="50" alt="Mouse0270" />
                        <h3><%= x.univ %>  <%= x.age %> / <%= x.number %></h3>
                        <h5><span>게시글 작성일</span> - <span> <%= x.created_at.in_time_zone("Seoul").strftime("%F %H:%M") %> </span> </h5>
                    </div>
                    <br>
                    <div style="text-align:center;">
                        <div style="font-family: 'Hanna';" display="block">
                            <% if x.replies.count == 3 %>
                            <p style="color:red;">댓글마감 <%= x.replies.count%>개 > </p>
                            <% else %>
                            <p>댓글 <%= x.replies.count%>개 > </p>
                            <% end %>
                        </div>
                        
                    </div>
                    <br>
                </div>
            </div>
        <% end %>
    <% end %> 
</div>

app/views/home/_mylog2.erb
<div class="row">	  
    <% @mylog2.reverse.each do |x| %>   
        <%= link_to reply_view_path(x.id), method:'post' do %>
        
        <% content_tag :div %>
        
            <div class="[ col-xs-12 col-sm-4 ] goodd">
                <div class="[ panel panel-default ] panel-google-plus">
                    
                    <div style="font-family: 'Hanna';" class="panel-heading">
                        <img class="[ img-circle pull-left ]" src="/assets/<%= x.univ %>.jpg" class="img-circle" width="50" alt="Mouse0270" />
                        <h3><%= x.univ %> <%= x.age %> / <%= x.number %></h3>
                        <h5><span>게시글 작성일</span> - <span> <%= x.created_at.in_time_zone("Seoul").strftime("%F %H:%M") %> </span> </h5>
                    </div>
                    <br>
                    <div style="text-align:center;">
                        <div style="font-family: 'Hanna';" display="block">
                            <% if x.replies.count == 3 %>
                            <p style="color:red;">댓글마감 <%= x.replies.count%>개 > </p>
                            <% else %>
                            <p>댓글 <%= x.replies.count%>개 > </p>
                            <% end %>
                        </div>
                        
                    </div>
                    <br>
                </div>
            </div>
        <% end %>
    <% end %> 
</div>

app/views/home/_posts2.erb
<div class="row">	  
    <% @posts2.reverse.each do |x| %>   
        <%= link_to reply_view_path(x.id), method:'post' do %>
        
        <% content_tag :div %>
        
            <div class="[ col-xs-12 col-sm-4 ] goodd">
                <div class="[ panel panel-default ] panel-google-plus">
                    
                    <div style="font-family: 'Hanna';" class="panel-heading">
                        <img class="[ img-circle pull-left ]" src="/assets/<%= x.univ %>.jpg" class="img-circle" width="50" alt="Mouse0270" />
                        <h3><%= x.univ %>  <%= x.age %> / <%= x.number %></h3>
                        <h5><span>게시글 작성일</span> - <span> <%= x.created_at.in_time_zone("Seoul").strftime("%F %H:%M") %> </span> </h5>
                    </div>
                    <br>
                    <div style="text-align:center;">
                        <div style="font-family: 'Hanna';" display="block">
                            <% if x.replies.count == 3 %>
                            <p style="color:red;">댓글마감 <%= x.replies.count%>개 > </p>
                            <% else %>
                            <p>댓글 <%= x.replies.count%>개 > </p>
                            <% end %>
                        </div>
                        
                    </div>
                    <br>
                </div>
            </div>
        <% end %>
    <% end %> 
</div>

app/views/home/_postsquare.erb
<div class="row">	  
    <% @posts3.reverse.each do |x| %>   
        <%= link_to reply_view_path(x.id), method:'post' do %>
        
        <% content_tag :div %>
        
            <div class="[ col-xs-12 col-sm-4 ] goodd">
                <div class="[ panel panel-default ] panel-google-plus">
                    
                    <div style="font-family: 'Hanna';" class="panel-heading">
                        <img class="[ img-circle pull-left ]" src="/assets/<%= x.univ %>.jpg" class="img-circle" width="50" alt="Mouse0270" />
                        <h3><%= x.univ %>  <%= x.age %> / <%= x.number %></h3>
                        <h5><span>게시글 작성일</span> - <span> <%= x.created_at.in_time_zone("Seoul").strftime("%F %H:%M") %> </span> </h5>
                    </div>
                    <br>
                    <div style="text-align:center;">
                        <div style="font-family: 'Hanna';" display="block">
                            <% if x.replies.count == 3 %>
                            <p style="color:red;">댓글마감 <%= x.replies.count%>개 > </p>
                            <% else %>
                            <p>댓글 <%= x.replies.count%>개 > </p>
                            <% end %>
                        </div>
                        
                    </div>
                    <br>
                </div>
            </div>
        <% end %>
    <% end %> 
</div>

app/views/home/_postwrite.erb
<div class="container" style="text-align:center">
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">만남적기</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
          <h4 class="modal-title">만남 정보를 적어주세요</h4>
        </div>
        
        <div class="modal-body">
          <div class="container form-group row" style="text-align:center;">
                <div class="col-lg-6">
                      
                <form action="/home/write" method="POST">
                    <input type="hidden" name="email" value="<%=current_user.email%>">
                    <input type="text" class="form-control" name="place" placeholder="만날 장소를 적어주세요(ex) 연세대 입구)"><br>
                    <input type="text" name="number" class="form-control" placeholder="몇명이 참여하는지 적어주세요(ex) 3명)"><br>
                    <textarea rows="4" cols="50" class="form-control" name="content"> </textarea><br>
                
                    <input type="submit" class="btn btn-primary" value="게시하기">
                    
                    <br> <br>
                </form>
                </div>
                
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

app/views/home/_signup.erb
<div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog modal-lg">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
          <h4 class="modal-title"><img src="/assets/오미팅로고.png" style="width:40px; height:40px;" class="img-circle">&nbsp 미팅새내기가 되어 또래 대학생들과 미팅을 해보세요!</h4>
        </div>
        
        <div class="modal-body">
          <div class="container form-group row" style="text-align:center;">
                
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

 
<div class="container">  
  <div class="row">
 
      <div class="col-lg-3 form-group">
    <%= f.label :email, "대학 E-mail" %><br>
    <%= f.email_field :email, autofocus: true, :placeholder => "e-mail을 입력해주세요", class: "form-control"%>  
      </div>

  </div>
</div>

<div class="container">  
  <div class="row">

      <div class="col-lg-3 form-group">
    <%=f.label :password, "Password" %><br>
    <%= f.password_field :password, autocomplete: "off", :placeholder => "비밀번호(8자리이상)를 입력해주세요", class: "form-control"%>
      </div>

      <div class="col-lg-3 form-group">
    <%=f.label :password_confirmation, "Confirm" %><br>
    <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "비밀번호를 확인합니다", class: "form-control"%>
      </div>  


  </div>
</div>

<div class="container">  
  <div class="row">

      <div class="col-lg-3 form-group">
        <%=f.label :univ , "대학교" %>
        <%= f.select( :univ, options_for_select([['대학교선택','대학교선택'],['연세대학교','연세대학교'],['인하대학교','인하대학교'],['이화여자대학교','이화여자대학교'],['숙명여자대학교','숙명여자대학교']], params[:univ]),{},{class: "form-control"}) %>
      </div>
      
      <div class="col-lg-3 form-group">
        <%= f.label :Face_img , "학과" %>
        <%= f.text_field :img, autofocus: true, :placeholder => "학과를 입력해주세요", class: "form-control" %>
      </div>


      <div class="col-lg-3 form-group">
        <%=f.label :age, "학번" %><br>
        <%= f.text_field :age, autofocus: true, :placeholder => "학번을 입력해주세요", class: "form-control" %>
      </div>

  </div>
</div>

<div class="container">  
  <div class="row">

      <div class="col-lg-3 form-group">
        <%=f.label :number , "연락처" %>
        <%= f.text_field :number, autofocus: true, :placeholder => "연락처를 입력해주세요", class: "form-control" %>
      </div>
      
    <div id="radio">
      <div class="col-lg-3">
        <%=f.label :성별 %><br>
          <%= f.radio_button :sex, "남자", :id=>"radio1", checked:true %>
          <label for="radio1" class="col-lg-6">남자</label>
          
          <%= f.radio_button :sex, "여자", :id=>"radio2" %>
          <label for="radio2" class="col-lg-6">여자</label>
      </div>
    </div>      


  </div>
</div>


<div class="container">  
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
       <%= f.submit "가입하기",class:"btn btn-lg btn-success" %>
    </div>   
  </div>
</div>  
<% end %>
                    </div>      
                

          </div>
        </div>

        
      </div>
      
    </div>
  </div>
  
        <script>
        $(function() {
          $( "#radio" ).buttonset();
        });
        </script>

app/views/home/post.html.erb
<h1>만남 정보를 적어주세요</h1> <br>
<div class="container form-group" style="text-align:center;">    
    <form action="/home/write" method="POST">
        <input type="hidden" class="form-control" value="<%= current_user.email %>" name="email" readonly> <br>
        <input type="hidden" class="form-control" value="<%= current_user.sex %>" name="sex" readonly> <br>
        <input type="hidden" class="form-control" value="<%= current_user.univ %>" name="univ" readonly> <br>
        <input type="text" class="form-control" name="place" placeholder="만날 장소를 적어주세요(ex) 연세대 입구)"><br>
        <input type="text" name="number" class="form-control" placeholder="몇명이 참여하는지 적어주세요(ex) 3명)"><br>
        <textarea rows="4" cols="50" class="form-control" name="content"> </textarea><br>
    
        <input type="submit" class="btn btn-primary" value="게시하기">
        
        <br> <br>
    </form>                
</div>

app/views/home/reply.html.erb
<%= render :partial => "home/header" %>      
<%= render :partial => "home/sidebar" %>
            
            
            
<% unless current_user.nil? %>

<section id="main-content" style="height:230px">
          <section class="wrapper" style="height:250px">

              <div class="row">
                  <div class="col-lg-12 main-chart" style="height:250;">
             <div class="row col-lg-10"><br>
            
        <div style="text-align:center;">
        
                    <div class="container-fluid">
                        <div class="row">
                        <div class="col-lg-2"></div>
                             <div class="col-lg-10 col-xs-12 col-sm-6 ">
                             
                                <div style="font-family: 'Hanna';" class="[ panel panel-default ] panel-google-plus">
                                    
                                    <div class="panel-heading">
                                        <img class="[ img-circle pull-left ]" src="/assets/<%= @detail.univ %>.jpg" class="img-circle" width="50" alt="Mouse0270" />
                                        <h3><%= @detail.univ %> <%= @detail.age %> / <%= @detail.sex %></h3>
                                        <h5><span>게시글 작성일</span> - <span> <%= @detail.created_at %> </span> </h5>
                                    </div>
                                    <div class="panel-body">
                                        <p>참여인원: <%= @detail.number %> / 만남장소(희망): <%= @detail.place %> </p>
                                        <p> <%= @detail.content %> </p>
                                    </div>
                                    
        
        
        
        
                                    <br>
        <% b = 33 %>
        <% a = 1 %>
        <% @detail.replies.each do |x| %>    
        
            <span class="label label-primary">댓글</span> <%= x.user.univ %> <%= x.user.img %> <%= x.user.age %> : <%= x.content %>
         
            <% if current_user.email == @detail.email %>
                 <button id="<%=a%>">번호 보기</button>
                <p id="<%=b%>" style="display:none;"><%= x.user.number %></p>
        
            <% end %>
            
            <script>
        
                
        
            $(document).ready(function(){
        
               $('#'+'<%=a%>').click(function(){
                   $('#'+'<%=b%>').fadeIn('slow');
                   $('#'+'<%=a%>').fadeOut('slow');
               })
              
            });
            
            </script>
            
            
            <% if current_user.email == @detail.email %> 
             <a href="/home/delete2/<%= x.id %>"> 삭제 </a>
            
            <% end %>
            <br>
        <%a = a + 1;%>
        <%b = b  + 1; %>
        <% end %>                            
        
        
        
        
        
        <!-- post_id > 4면 밑에부분이 안보이도록만 해주면서 마감되었습니다를 넣어주면 될거같애 -->
        
        <!-- 리플쓴 사람 email찾아 == 현재 로그인한 사람 email(current_user.email) 이면 이미 등록하셨습니다를 넣어주자 -->
        
        
        <% if @detail.replies.count < 3 %>
        

            <form action="/home/write_reply" method="POST" class="form-inline">
                <input type="hidden" name="univ" value="<%=@detail.univ%>">
                <input type="hidden" name="age" value="<%=@detail.age%>">
                <input type="hidden" name="img" value="<%=@detail.img%>">
                <input type="hidden" name="post_id" value="<%=@detail.id%>">
                <br>
                <input type="text" name="myreply" class="form-control"  placeholder="자신을 소개해주세요^^">
                <input type="submit" value="리플달기" class="form-control">
              
            </form>
        <% else %>
        
            <h1> 선착순 댓글이 모두 마감되었습니다. </h1>
            
        <% end %>
        
        <br>
        <form action="/home/two" method="POST">
            <input type="submit" value="돌아가기" class="form-control btn-warning">
        </form>
        
        <% if current_user.id == @detail.id %>
        
        <a href="/home/modify2/<%=@detail.id%>"> 수정 </a> &nbsp
        <a href="/home/delete/<%=@detail.id%>"> 삭제 </a>
        
        <% end %>
        
        
        </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
        
        <!-- 우리가 우선 컨트롤러에 @reply = Reply.find([:id])로 받아준다음에, @reply.email하면 될거같은데 그치? -->

<% end %>

app/views/home/test4.erb
<form action="/home/three" method="POST">
                        <input id="autocomplete" name=search type="text">
                        <input type="submit" value="검색하기">
 </form>

app/views/home/three.html.erb
<%= render :partial => "home/header" %>      
<%= render :partial => "home/sidebar" %>

<% unless current_user.nil? %>

      
    <% if params[:search2].nil? && params[:search].nil? %>
      <section id="main-content" style="height:230px">
          <section class="wrapper" style="height:250px">
    
              <div class="row">
                  <div class="col-lg-12 main-chart" style="height:250;">
                    
                           <br>
                        <div class="container-fluid" style="text-align:center">
                          <!-- Trigger the modal with a button -->
                          
                           <h3>최신순</h3>
            <%= render :partial => "home/postsquare" %>
                                             
                        </div>
                    
                  </div>
              </div>
                  
          </section>
      </section>
 
    <% elsif params[:search2].nil? %>
      <section id="main-content" style="height:230px">
          <section class="wrapper" style="height:250px">
    
              <div class="row">
                  <div class="col-lg-12 main-chart" style="height:250;">
                    
                           <br>
                        <div class="container-fluid" style="text-align:center">
                          <!-- Trigger the modal with a button -->
                          
                           <h3>내 학교 목록</h3>
          	 <%= render :partial => "home/mylog" %>
                                             
                        </div>
                    
                  </div>
              </div>
                  
          </section>
      </section>



    <% elsif params[:search].nil? %>
      <section id="main-content" style="height:230px">
        <section class="wrapper" style="height:250px">
    
              <div class="row">
                  <div class="col-lg-12 main-chart" style="height:250;">
                    
                           <br>
                        <div class="container-fluid" style="text-align:center">
                          <!-- Trigger the modal with a button -->
                          
      <h3>내가 쓴 게시글 목록</h3>
          	 <%= render :partial => "home/mylog2" %>
                                             
                        </div>
                    
                  </div>
              </div>
                  
          </section>
      </section>
    <% end %>          
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>